---
postgresql_client_windows_version: 18.6-1
postgresql_client_windows_installer_url: >-
  https://get.enterprisedb.com/postgresql/postgresql-18.6-1-windows-x64.exe
postgresql_client_windows_installer_sha256: >-
  CAE561E98D09F3F4A1A95759249240F86F66D71DCF33D14B6F7BE894078401D1
postgresql_client_windows_install_dir: C:\Program Files\PostgreSQL\18
