---
- name: Dotweave | Tap the Tinyrack Homebrew repository
  ansible.builtin.include_role:
    name: brew_tap
  vars:
    brew_tap_names:
      - tinyrack-net/tap

- name: Dotweave | Install dotweave from Homebrew
  when: "'tinyrack-net/tap/dotweave' not in (brew_installed_formulae | default([]))"
  community.general.homebrew:
    name: tinyrack-net/tap/dotweave
    state: latest
    update_homebrew: true
  become: false

- name: Dotweave | Upgrade the installed dotweave formula
  when: "'tinyrack-net/tap/dotweave' in (brew_installed_formulae | default([]))"
  community.general.homebrew:
    name: tinyrack-net/tap/dotweave
    state: latest
    update_homebrew: true
  become: false
