---
- name: Download Visual Studio Code deb package
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['distribution'] in ['Ubuntu', 'Debian']
    - ansible_facts['architecture'] in ['x86_64', 'amd64']
  ansible.builtin.get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: /tmp/code-stable-linux-deb-x64.deb
    mode: '0644'

- name: Install Visual Studio Code
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['distribution'] in ['Ubuntu', 'Debian']
    - ansible_facts['architecture'] in ['x86_64', 'amd64']
  ansible.builtin.apt:
    deb: /tmp/code-stable-linux-deb-x64.deb
    state: present
  become: true
