- name: Tap a opencode repository, state present
  community.general.homebrew_tap:
    name: sst/tap

- name: Install Brew Packages
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  become: false
  with_items:
    - { name: sst/tap/opencode, state: present }
