---
# https://www.jetbrains.com/help/toolbox-app/installation.html lists
# "libfontconfig" generically; the corresponding Ubuntu runtime package is
# libfontconfig1.
jetbrains_toolbox_ubuntu_packages:
  - libxi6
  - libxrender1
  - libxtst6
  - mesa-utils
  - libfontconfig1
  - libgtk-3-bin
  - tar
  - dbus-user-session
  - libxcb-keysyms1

jetbrains_toolbox_linux_install_dir: >-
  {{ ansible_facts['env']['HOME'] }}/.local/share/JetBrains/Toolbox
