---
- name: Android | Assert the macOS architecture is supported
  ansible.builtin.assert:
    that:
      - ansible_facts['architecture'] in ['arm64', 'x86_64']
    fail_msg: >-
      Google's Android SDK Command-line Tools do not support macOS
      {{ ansible_facts['architecture'] }}.
    quiet: true

- name: Android | Define the macOS SDK installation
  ansible.builtin.set_fact:
    android_sdk_root_effective: >-
      {{ android_sdk_root | default(ansible_facts['env']['HOME'] ~ '/Library/Android/sdk', true) }}
    android_cmdline_tools_platform: >-
      {{ 'mac_arm64' if ansible_facts['architecture'] == 'arm64' else 'mac_x86_64' }}

- name: Android | Resolve the latest Command-line Tools
  ansible.builtin.include_tasks: resolve_cmdline_tools.yml

- name: Android | Install the SDK
  ansible.builtin.include_tasks: unix.yml
