---
- name: Android | Assert the macOS architecture is supported
  ansible.builtin.assert:
    that:
      - ansible_facts['architecture'] in ['arm64', 'x86_64']
    fail_msg: >-
      Google's Android SDK Command-line Tools do not support macOS
      {{ ansible_facts['architecture'] }}.
    quiet: true

- name: Android | Define the macOS SDK installation
  ansible.builtin.set_fact:
    android_sdk_root_effective: >-
      {{ android_sdk_root | default(ansible_facts['env']['HOME'] ~ '/Library/Android/sdk', true) }}
    android_cmdline_tools_platform: >-
      {{ 'mac_arm64' if ansible_facts['architecture'] == 'arm64' else 'mac_x86_64' }}
    android_cmdline_tools_checksum_key: >-
      {{ 'darwin_arm64' if ansible_facts['architecture'] == 'arm64' else 'darwin_x86_64' }}

- name: Android | Define the macOS Command-line Tools artifact
  ansible.builtin.set_fact:
    android_cmdline_tools_url: >-
      https://dl.google.com/android/repository/commandlinetools-{{
      android_cmdline_tools_platform }}-{{ android_cmdline_tools_version }}_latest.zip
    android_cmdline_tools_checksum: >-
      sha256:{{ android_cmdline_tools_checksums[android_cmdline_tools_checksum_key] }}

- name: Android | Install the SDK
  ansible.builtin.include_tasks: unix.yml
