---
- name: Restart RustDesk on Linux
  ansible.builtin.systemd_service:
    name: rustdesk
    state: restarted
  become: true

- name: Restart RustDesk on macOS
  ansible.builtin.command:
    argv:
      - launchctl
      - kickstart
      - -k
      - system/com.carriez.RustDesk_service
  become: true

- name: Restart RustDesk on Windows
  ansible.windows.win_service:
    name: RustDesk
    state: restarted
