---
- name: Install Python3 (Brew)
  when: python_brew_package not in (brew_installed_formulae | default([]))
  become: false
  community.general.homebrew:
    name: "{{ python_brew_package }}"
    state: present
  loop:
    - python
    - pipx
  loop_control:
    loop_var: python_brew_package
