---
- name: Install Python3 (Apt)
  become: true
  ansible.builtin.apt:
    name: "{{ python_apt_package }}"
    state: present
  loop:
    - python3
    - pipx
    - build-essential
  loop_control:
    loop_var: python_apt_package
