---
- name: Libreoffice | Install LibreOffice (Homebrew cask)
  when: "'libreoffice' not in (brew_installed_casks | default([]))"
  community.general.homebrew_cask:
    name: libreoffice
    state: present
  become: false
