---
- name: RustDesk | Read current server options
  ansible.builtin.command:
    argv:
      - "{{ rustdesk_cli_path }}"
      - --option
      - "{{ item.key }}"
  loop: "{{ rustdesk_server_options | dict2items }}"
  register: rustdesk_current_server_options
  changed_when: false
  check_mode: false
  become: true
  no_log: true

- name: RustDesk | Apply changed server options
  ansible.builtin.command:
    argv:
      - "{{ rustdesk_cli_path }}"
      - --option
      - "{{ item.item.key }}"
      - "{{ item.item.value }}"
  loop: "{{ rustdesk_current_server_options.results }}"
  loop_control:
    label: "{{ item.item.key }}"
  when: item.stdout | trim != item.item.value
  changed_when: true
  become: true
  no_log: true
  notify: "{{ rustdesk_restart_handler }}"
