---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh

- name: Install tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - direnv
    - fzf

- name: Setup default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
