# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
PackageIdentifier: NerdFonts.Agave
PackageVersion: 3.5.1
PackageLocale: en-US
Publisher: Nerd Fonts
PublisherUrl: https://www.nerdfonts.com/
PublisherSupportUrl: https://github.com/ryanoasis/nerd-fonts/issues
PackageName: Agave Nerd Font
PackageUrl: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Agave
License: SIL Open Font License 1.1
LicenseUrl: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Agave/LICENSE
ShortDescription: Agave patched with the Nerd Fonts glyph set
ManifestType: defaultLocale
ManifestVersion: 1.12.0
