# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: NerdFonts.Agave
PackageVersion: 3.5.1
InstallerType: zip
NestedInstallerType: font
Scope: user
UpgradeBehavior: install
Installers:
  - Architecture: neutral
    InstallerUrl: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.5.1/Agave.zip
    InstallerSha256: F53C8052BD117ADED74055FEDF41351F1CB61F0B26BCCB8B901A170385170837
    NestedInstallerFiles:
      - RelativeFilePath: AgaveNerdFont-Bold.ttf
      - RelativeFilePath: AgaveNerdFont-Regular.ttf
      - RelativeFilePath: AgaveNerdFontMono-Bold.ttf
      - RelativeFilePath: AgaveNerdFontMono-Regular.ttf
      - RelativeFilePath: AgaveNerdFontPropo-Bold.ttf
      - RelativeFilePath: AgaveNerdFontPropo-Regular.ttf
ManifestType: installer
ManifestVersion: 1.12.0
