---
# No windows.yml: kubeseal has no winget package at all.
- name: Kubeseal | Install kubeseal (brew)
  when: "'kubeseal' not in (brew_installed_formulae | default([]))"
  community.general.homebrew:
    name: kubeseal
    state: present
  become: false
