---
- name: NordVPN | Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ nordvpn_task_file }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}.yml"
        - default.yml
      skip: true
  loop_control:
    loop_var: nordvpn_task_file
