- name: Install Dependencies (Homebrew)
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  become: false
  with_items:
    - gh

- name: Install dependencies
  when: ansible_facts['distribution'] == 'Fedora'
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - git-delta
    - git-credential-libsecret
    - git-credential-oauth

- name: Import GPG private key
  ansible.builtin.copy:
    src: gpg.asc
    dest: /tmp/gpg.asc
    mode: '0600'

- name: Import GPG key into keyring
  ansible.builtin.command:
    cmd: gpg --import /tmp/gpg.asc
  register: gpg_import_result
  changed_when: "'imported: 1' in gpg_import_result.stderr or 'new keys: 1' in gpg_import_result.stderr"

- name: Remove temporary GPG key file
  ansible.builtin.file:
    path: /tmp/gpg.asc
    state: absent
