- name: Install Dependencies (Homebrew)
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  become: false
  with_items:
    - gh

- name: Install dependencies
  when: ansible_facts['distribution'] == 'Fedora'
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - git-delta
    - git-credential-libsecret
    - git-credential-oauth
