---
- name: Discord | Install Discord (Flatpak)
  when: "'com.discordapp.Discord' not in (flatpak_installed_ids | default([]))"
  become: true
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
