- name: Install Zellij
  community.general.homebrew:
    name: zellij
    state: present

- name: Tmux | Install tmux from apt
  when: ansible_facts['os_family'] == 'Ubuntu'
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Tmux | Install tmux from dnf
  when: ansible_facts['os_family'] == 'Fedora'
  become: true
  ansible.builtin.dnf:
    name: tmux
    state: present

- name: Tmux | Install tmux from homebrew
  when: ansible_facts['os_family'] == 'Darwin'
  community.general.homebrew:
    name: tmux
    state: present
  become: false

- name: Tmux | Install tmux package manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux/plugins/tpm"
    update: true
    clone: true
