- name: Install tmux from apt
  when: ansible_os_family == 'Ubuntu'
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Install tmux from dnf
  when: ansible_os_family == 'Fedora'
  become: true
  ansible.builtin.dnf:
    name: tmux
    state: present

- name: Install tmux from homebrew
  when: ansible_os_family == 'Darwin'
  community.general.homebrew:
    name: tmux
    state: present
  become: false

- name: Install tmux package manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.tmux/plugins/tpm"
    update: true
    clone: true
