- name: Tmux | Install tmux from apt
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Tmux | Install tmux from homebrew
  when: ansible_facts['os_family'] == 'Darwin'
  community.general.homebrew:
    name: tmux
    state: present
  become: false
