- name: Check Node Installation
  ansible.builtin.stat:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/share/nvm/v{{ node_version }}"
  register: check_node_result

- name: Install Bun
  community.general.homebrew_tap:
    name: oven-sh/bun

- name: Install Brew Packages
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  become: false
  with_items:
    - { name: oven-sh/bun/bun, state: present }
