- name: Ai | Tap
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  become: false
  with_items:
    - anomalyco/tap
    - charmbracelet/tap

- name: Ai | Install Tools
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  become: false
  with_items:
    - { name: anomalyco/tap/opencode, state: present }
    - { name: codex, state: present }
    - { name: copilot-cli, state: present }

- name: Ai | Check if Claude is already installed
  ansible.builtin.stat:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/claude"
  register: ai_claude_exists
  become: false

- name: Ai | Download Claude Installer
  when: not ai_claude_exists.stat.exists
  ansible.builtin.get_url:
    url: https://claude.ai/install.sh
    dest: /tmp/claude-install.sh
    mode: "0755"
    force: "yes"
  become: false

- name: Ai | Install Claude Code
  when: not ai_claude_exists.stat.exists
  ansible.builtin.command: /tmp/claude-install.sh
  changed_when: true
  become: false
