- name: Install required dependencies
  become: true
  when: ansible_facts['distribution'] == 'Ubuntu'
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - build-essential

- name: Install the latest version of Apache
  become: true
  when: ansible_facts['distribution'] == 'Fedora'
  ansible.builtin.dnf5:
    name: "{{ item }}"
    state: present
  with_items:
    - "@development-tools"
    - curl
    - git
