- name: Install required dependencies
  become: true
  when: ansible_facts['distribution'] == 'Ubuntu'
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - build-essential
