---
- name: Agave Nerd Font | Install the official font archive
  ansible.builtin.include_tasks: unix.yml
  vars:
    agave_nerd_font_install_dir: >-
      {{ ansible_facts['env']['HOME'] }}/Library/Fonts
