---
- name: Install Neovim tooling (winget)
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_packages:
      - Neovim.Neovim
      - BurntSushi.ripgrep.MSVC
      - sharkdp.fd
      - JesseDuffield.lazygit
